#include "xcv_wrapper.h"
#include "xcv_engine/src/lib.rs.h" // generated by cxx
#include <iostream>
#include <string>
#include <vector>
#include <cctype>
#include <stdexcept>
#include <algorithm>
#include <utility>

// Helper to parse cell coordinate (e.g., "A1" -> col=0, row=0)
bool parse_cell_ref(const std::string& ref, int& col, int& row) {
    size_t i = 0;
    while (i < ref.size() && std::isalpha(static_cast<unsigned char>(ref[i]))) {
        i++;
    }
    if (i == 0 || i == ref.size()) return false;
    
    std::string col_part = ref.substr(0, i);
    std::string row_part = ref.substr(i);
    
    int c = 0;
    for (char ch : col_part) {
        c = c * 26 + (std::toupper(static_cast<unsigned char>(ch)) - 'A' + 1);
    }
    col = c - 1;
    
    try {
        row = std::stoi(row_part) - 1;
    } catch (...) {
        return false;
    }
    return true;
}

// Helper to format 0-based col/row back to cell ID string
std::string format_cell_ref(int col, int row) {
    std::string col_str;
    int temp = col + 1;
    while (temp > 0) {
        int m = (temp - 1) % 26;
        col_str.insert(col_str.begin(), static_cast<char>('A' + m));
        temp = (temp - m) / 26;
    }
    return col_str + std::to_string(row + 1);
}

// A recursive descent parser for basic spreadsheet formulas
class FormulaParser {
    std::string src;
    size_t pos = 0;
    const XcvSheet& sheet;
    std::vector<std::string>& visited;

    void skip_whitespace() {
        while (pos < src.size() && std::isspace(static_cast<unsigned char>(src[pos]))) {
            pos++;
        }
    }

    char peek() {
        skip_whitespace();
        if (pos >= src.size()) return '\0';
        return src[pos];
    }

    char get() {
        skip_whitespace();
        if (pos >= src.size()) return '\0';
        return src[pos++];
    }

    bool match(char expected) {
        if (peek() == expected) {
            get();
            return true;
        }
        return false;
    }

    // Helper to evaluate a cell reference recursively
    double get_cell_value_recursive(const std::string& cell_id) {
        // Detect circular reference
        if (std::find(visited.begin(), visited.end(), cell_id) != visited.end()) {
            throw std::runtime_error("Circular reference detected: " + cell_id);
        }

        rust::String formula_rust = sheet.get_cell_formula(cell_id);
        std::string formula(formula_rust.data(), formula_rust.size());
        if (!formula.empty()) {
            visited.push_back(cell_id);
            try {
                FormulaParser sub_parser(formula, sheet, visited);
                double val = sub_parser.parse();
                visited.pop_back();
                return val;
            } catch (...) {
                visited.pop_back();
                throw;
            }
        } else {
            return sheet.get_cell_value(cell_id);
        }
    }

public:
    FormulaParser(std::string s, const XcvSheet& sh, std::vector<std::string>& vis) 
        : src(std::move(s)), sheet(sh), visited(vis) {
        // Strip leading '=' if present
        if (!src.empty() && src[0] == '=') {
            src = src.substr(1);
        }
    }

    double parse() {
        double val = parse_expression();
        skip_whitespace();
        if (pos < src.size()) {
            throw std::runtime_error("Unexpected characters at end of formula");
        }
        return val;
    }

private:
    double parse_expression() {
        double val = parse_term();
        while (true) {
            if (match('+')) {
                val += parse_term();
            } else if (match('-')) {
                val -= parse_term();
            } else {
                break;
            }
        }
        return val;
    }

    double parse_term() {
        double val = parse_factor();
        while (true) {
            if (match('*')) {
                val *= parse_factor();
            } else if (match('/')) {
                double divisor = parse_factor();
                if (divisor == 0.0) throw std::runtime_error("Division by zero");
                val /= divisor;
            } else {
                break;
            }
        }
        return val;
    }

    double parse_factor() {
        skip_whitespace();
        char c = peek();

        if (std::isdigit(static_cast<unsigned char>(c)) || c == '.') {
            return parse_number();
        } else if (match('(')) {
            double val = parse_expression();
            if (!match(')')) {
                throw std::runtime_error("Missing closing parenthesis");
            }
            return val;
        } else if (match('-')) {
            return -parse_factor();
        } else if (match('+')) {
            return parse_factor();
        } else if (std::isalpha(static_cast<unsigned char>(c))) {
            return parse_function_or_cell();
        } else {
            throw std::runtime_error(std::string("Unexpected character: '") + c + "'");
        }
    }

    double parse_number() {
        size_t start = pos;
        bool dot = false;
        while (pos < src.size()) {
            char c = src[pos];
            if (std::isdigit(static_cast<unsigned char>(c))) {
                pos++;
            } else if (c == '.' && !dot) {
                dot = true;
                pos++;
            } else {
                break;
            }
        }
        std::string num_str = src.substr(start, pos - start);
        return std::stod(num_str);
    }

    double parse_function_or_cell() {
        std::string name;
        while (pos < src.size() && std::isalnum(static_cast<unsigned char>(src[pos]))) {
            name += src[pos++];
        }
        std::transform(name.begin(), name.end(), name.begin(), ::toupper);

        if (match('(')) {
            std::vector<double> args;
            if (peek() != ')') {
                while (true) {
                    // Check for cell range (e.g. A1:B3)
                    size_t saved_pos = pos;
                    skip_whitespace();
                    std::string first_id;
                    while (pos < src.size() && std::isalnum(static_cast<unsigned char>(src[pos]))) {
                        first_id += src[pos++];
                    }
                    skip_whitespace();
                    if (pos < src.size() && src[pos] == ':') {
                        pos++; // consume ':'
                        skip_whitespace();
                        std::string second_id;
                        while (pos < src.size() && std::isalnum(static_cast<unsigned char>(src[pos]))) {
                            second_id += src[pos++];
                        }
                        
                        int start_col, start_row, end_col, end_row;
                        if (parse_cell_ref(first_id, start_col, start_row) &&
                            parse_cell_ref(second_id, end_col, end_row)) {
                            int min_col = std::min(start_col, end_col);
                            int max_col = std::max(start_col, end_col);
                            int min_row = std::min(start_row, end_row);
                            int max_row = std::max(start_row, end_row);
                            
                            for (int c = min_col; c <= max_col; ++c) {
                                for (int r = min_row; r <= max_row; ++r) {
                                    std::string cell_id = format_cell_ref(c, r);
                                    args.push_back(get_cell_value_recursive(cell_id));
                                }
                            }
                        } else {
                            throw std::runtime_error("Invalid range: " + first_id + ":" + second_id);
                        }
                    } else {
                        pos = saved_pos;
                        args.push_back(parse_expression());
                    }

                    if (match(',')) {
                        continue;
                    } else if (peek() == ')') {
                        break;
                    } else {
                        throw std::runtime_error("Expected ',' or ')' in function arguments");
                    }
                }
            }
            if (!match(')')) {
                throw std::runtime_error("Missing closing parenthesis in function call");
            }

            if (name == "SUM") {
                double sum = 0.0;
                for (double v : args) sum += v;
                return sum;
            } else if (name == "AVERAGE") {
                if (args.empty()) return 0.0;
                double sum = 0.0;
                for (double v : args) sum += v;
                return sum / args.size();
            } else if (name == "MIN") {
                if (args.empty()) return 0.0;
                return *std::min_element(args.begin(), args.end());
            } else if (name == "MAX") {
                if (args.empty()) return 0.0;
                return *std::max_element(args.begin(), args.end());
            } else {
                throw std::runtime_error("Unknown function: " + name);
            }
        } else {
            int col, row;
            if (parse_cell_ref(name, col, row)) {
                return get_cell_value_recursive(name);
            } else {
                throw std::runtime_error("Unknown identifier: " + name);
            }
        }
    }
};

double FormulaEngine::evaluate_formula(rust::Str formula, const XcvSheet& sheet) const {
    std::string f_str(formula.data(), formula.size());
    std::cout << "[C++ Core] ⚙️  Evaluating: " << f_str << std::endl;
    try {
        std::vector<std::string> visited;
        FormulaParser parser(f_str, sheet, visited);
        return parser.parse();
    } catch (const std::exception& e) {
        std::cerr << "[C++ Error] ❌ " << e.what() << std::endl;
        return 0.0;
    }
}

std::unique_ptr<FormulaEngine> new_engine() {
    return std::make_unique<FormulaEngine>();
}
