#!/bin/bash
# grinder_pipeline.sh v1.0
# Ring-0 Sovereign Data Grinder - Kali Linux master orchestration harness
# Recursively processes target directory through extractor -> sanitizer pipe
# Appends structured output to Master_Ring0.md

set -euo pipefail

TARGET_DIR="${1:-./raw_data}"
OUTPUT_MD="Master_Ring0.md"
EXTRACTOR="./ring0_extractor.py"
SANITIZER="./api_sanitizer.py"

echo "[Ring-0] Initializing Sovereign Data Refinery Pipeline" >&2
echo "[Ring-0] Target directory: $TARGET_DIR" >&2
echo "[Ring-0] Master output: $OUTPUT_MD" >&2

if [ ! -d "$TARGET_DIR" ]; then
    echo "[Ring-0] ERROR: Target directory does not exist: $TARGET_DIR" >&2
    exit 1
fi

chmod +x "$EXTRACTOR" "$SANITIZER" 2>/dev/null || true

# Initialize master corpus
{
    echo "# Ring-0 Master Data Corpus - $(date -Iseconds)"
    echo ""
    echo "**Generated by:** Khawrizm-Data-Refinery v1.0 | Sulaiman Alshammari | KHAWRIZM Forensic Labs"
    echo "**Architecture:** Ring-0 Master Synthesizer"
    echo "**Classification:** Sovereign / Zero-Telemetry / Air-Gapped Extraction Phase"
    echo ""
    echo "---"
    echo ""
} > "$OUTPUT_MD"

file_count=0
processed_count=0

while IFS= read -r -d $'\0' file; do
    ((file_count++))
    echo "[Ring-0] Processing file $file_count: $file" >&2

    # Extract offline
    extracted="$(python3 "$EXTRACTOR" "$file" 2>/dev/null || echo "")"

    if [ -z "$extracted" ] || [[ "$extracted" == *"EXTRACTION ERROR"* ]]; then
        echo "[Ring-0] Skipping (empty or extraction failure): $file" >&2
        continue
    fi

    # Pipe directly to sanitizer (stdin mode)
    sanitized="$(echo "$extracted" | python3 "$SANITIZER" - 2>/dev/null || echo "")"

    if [ -n "$sanitized" ] && [[ "$sanitized" != *"No content"* ]]; then
        {
            echo "$sanitized"
            echo ""
            echo "---"
            echo ""
        } >> "$OUTPUT_MD"
        ((processed_count++))
        echo "[Ring-0] Appended sanitized section from: $file" >&2
    else
        echo "[Ring-0] No valid sanitized output (dropped) for: $file" >&2
    fi

done < <(find "$TARGET_DIR" -type f \( ! -name "$(basename "$OUTPUT_MD")" -a ! -name "*.py" -a ! -name "*.sh" -a ! -name ".*" \) -print0)

echo "" >&2
echo "[Ring-0] Pipeline complete." >&2
echo "[Ring-0] Files scanned: $file_count | Sections written: $processed_count" >&2
echo "[Ring-0] Master_Ring0.md size: $(wc -c < "$OUTPUT_MD") bytes" >&2
echo "[Ring-0] Status: READY FOR NOTEBOOKLM" >&2
