#!/bin/bash
# grinder_pipeline.sh v1.1
# Ring-0 Sovereign Data Grinder - Kali Linux master orchestration harness
# Recursively processes target directory through extractor -> sanitizer pipe
# Supports --airgap mode for fully local inference (no external bytes)
# Appends structured output to Master_Ring0.md + GPG provenance signature

set -euo pipefail

# Parse flags and target
AIRGAP=false
TARGET_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --airgap|--local|-a)
      AIRGAP=true
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [--airgap] [target_directory]"
      echo "  --airgap   Route to airgapped_sanitizer.py (local Ollama)"
      exit 0
      ;;
    *)
      if [ -z "$TARGET_DIR" ]; then
        TARGET_DIR="$1"
      fi
      shift
      ;;
  esac
done

TARGET_DIR="${TARGET_DIR:-./raw_data}"
OUTPUT_MD="Master_Ring0.md"
EXTRACTOR="./ring0_extractor.py"

if $AIRGAP; then
  SANITIZER="./airgapped_sanitizer.py"
  MODE="AIRGAPPED (local Ollama)"
else
  SANITIZER="./api_sanitizer.py"
  MODE="EXTERNAL API"
fi

echo "[Ring-0] Initializing Sovereign Data Refinery Pipeline (v1.1)" >&2
echo "[Ring-0] Mode: $MODE" >&2
echo "[Ring-0] Target directory: $TARGET_DIR" >&2
echo "[Ring-0] Master output: $OUTPUT_MD" >&2

if [ ! -d "$TARGET_DIR" ]; then
    echo "[Ring-0] ERROR: Target directory does not exist: $TARGET_DIR" >&2
    exit 1
fi

chmod +x "$EXTRACTOR" "$SANITIZER" 2>/dev/null || true

# Initialize master corpus
{
    echo "# Ring-0 Master Data Corpus - $(date -Iseconds)"
    echo ""
    echo "**Generated by:** Khawrizm-Data-Refinery v1.1 | Sulaiman Alshammari | KHAWRIZM Forensic Labs"
    echo "**Architecture:** Ring-0 Master Synthesizer | Mode: $MODE"
    echo "**Classification:** Sovereign / Zero-Telemetry / Air-Gapped Extraction Phase"
    echo ""
    echo "---"
    echo ""
} > "$OUTPUT_MD"

file_count=0
processed_count=0

while IFS= read -r -d $'\0' file; do
    ((file_count++))
    echo "[Ring-0] Processing file $file_count: $file" >&2

    # Extract offline
    extracted="$(python3 "$EXTRACTOR" "$file" 2>/dev/null || echo "")"

    if [ -z "$extracted" ] || [[ "$extracted" == *"EXTRACTION ERROR"* ]]; then
        echo "[Ring-0] Skipping (empty or extraction failure): $file" >&2
        continue
    fi

    # Pipe directly to selected sanitizer (stdin mode)
    sanitized="$(echo "$extracted" | python3 "$SANITIZER" - 2>/dev/null || echo "")"

    if [ -n "$sanitized" ] && [[ "$sanitized" != *"No content"* ]]; then
        {
            echo "$sanitized"
            echo ""
            echo "---"
            echo ""
        } >> "$OUTPUT_MD"
        ((processed_count++))
        echo "[Ring-0] Appended sanitized section from: $file" >&2
    else:
        echo "[Ring-0] No valid sanitized output (dropped) for: $file" >&2
    fi

done < <(find "$TARGET_DIR" -type f \( ! -name "$(basename "$OUTPUT_MD")" -a ! -name "*.py" -a ! -name "*.sh" -a ! -name ".*" \) -print0)

echo "" >&2
echo "[Ring-0] Pipeline complete." >&2
echo "[Ring-0] Files scanned: $file_count | Sections written: $processed_count" >&2
echo "[Ring-0] Master_Ring0.md size: $(wc -c < "$OUTPUT_MD") bytes" >&2

# Cryptographic Supply Chain Integrity (OpenSSF LFD121/LFD125 aligned)
echo "[Ring-0] Executing cryptographic provenance signing..." >&2
if command -v gpg >/dev/null 2>&1; then
    if gpg --batch --yes --detach-sign --armor --output "${OUTPUT_MD}.sig" "$OUTPUT_MD" 2>/dev/null; then
        echo "[Ring-0] GPG signature created: ${OUTPUT_MD}.sig" >&2
        echo "[Ring-0] Verify: gpg --verify ${OUTPUT_MD}.sig ${OUTPUT_MD}" >&2
    else
        echo "[Ring-0] GPG signing skipped (no usable default secret key or agent issue)" >&2
    fi
else
    echo "[Ring-0] WARNING: gpg not found in PATH. Install gnupg for supply-chain signatures." >&2
fi

echo "[Ring-0] Status: READY FOR NOTEBOOKLM + VERIFIABLE PROVENANCE" >&2
