#!/bin/bash
# grinder_pipeline.sh v1.3
# Ring-0 Sovereign Data Grinder - now executes hardware-accelerated ring0_core Rust binary
# Replaces Python GIL-bound extractor. Pipes to airgapped_sanitizer. flock + GPG preserved.

set -euo pipefail

AIRGAP=false
PARALLEL=false
TARGET_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --airgap|--local|-a)
      AIRGAP=true
      shift
      ;;
    --parallel|-p)
      PARALLEL=true
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [--airgap] [--parallel] [target_directory]"
      exit 0
      ;;
    *)
      if [ -z "$TARGET_DIR" ]; then
        TARGET_DIR="$1"
      fi
      shift
      ;;
  esac
done

TARGET_DIR="${TARGET_DIR:-./raw_data}"
OUTPUT_MD="Master_Ring0.md"
EXTRACTOR="./ring0_core"   # Rust binary (built via build_sovereign.sh)

if $AIRGAP; then
  SANITIZER="./airgapped_sanitizer.py"
  MODE="AIRGAPPED + RUST CORE (memory-safe)"
else
  SANITIZER="./api_sanitizer.py"
  MODE="EXTERNAL + RUST CORE"
fi

if $PARALLEL; then
  MODE+=" + PARALLEL (xargs + flock)"
fi

echo "[Ring-0 v1.3] Initializing Sovereign Data Refinery Pipeline" >&2
echo "[Ring-0] Mode: $MODE" >&2
echo "[Ring-0] Target: $TARGET_DIR | Output: $OUTPUT_MD" >&2

if [ ! -d "$TARGET_DIR" ]; then
    echo "[Ring-0] ERROR: $TARGET_DIR missing" >&2
    exit 1
fi

if [ ! -x "$EXTRACTOR" ]; then
    echo "[Ring-0] FATAL: $EXTRACTOR not found or not executable. Run ./build_sovereign.sh first." >&2
    exit 1
fi

chmod +x "$SANITIZER" 2>/dev/null || true

{
    echo "# Ring-0 Master Data Corpus - $(date -Iseconds)"
    echo ""
    echo "**Generated by:** Khawrizm-Data-Refinery v1.3 | Sulaiman Alshammari | KHAWRIZM Forensic Labs"
    echo "**Architecture:** Ring-0 Master Synthesizer (Rust core) | Mode: $MODE"
    echo "**Classification:** Sovereign / Zero-Telemetry / Kernel Airgap / Memory-Safe Extraction"
    echo ""
    echo "---"
    echo ""
} > "$OUTPUT_MD"

file_count=0
processed_count=0
LOCKFILE="${OUTPUT_MD}.lock"
touch "$LOCKFILE"

process_one() {
    local file="$1"
    local extracted sanitized
    extracted="$( "$EXTRACTOR" "$file" 2>/dev/null || echo "" )"
    if [ -z "$extracted" ] || [[ "$extracted" == *"EXTRACTION ERROR"* ]] || [[ "$extracted" == *"Not found"* ]]; then
        return 1
    fi
    sanitized="$(echo "$extracted" | python3 "$SANITIZER" - 2>/dev/null || echo "" )"
    if [ -n "$sanitized" ] && [[ "$sanitized" != *"No content"* ]]; then
        (
            flock -x 200
            {
                echo "$sanitized"
                echo ""
                echo "---"
                echo ""
            } >> "$OUTPUT_MD"
        ) 200>"$LOCKFILE"
        echo "[Ring-0] Appended (Rust): $file" >&2
        return 0
    fi
    return 1
}

export -f process_one
export EXTRACTOR SANITIZER OUTPUT_MD LOCKFILE

if $PARALLEL; then
    find "$TARGET_DIR" -type f \( ! -name "$(basename "$OUTPUT_MD")" -a ! -name "*.py" -a ! -name "*.sh" -a ! -name ".*" \) -print0 | \
        xargs -0 -P "$(nproc)" -I {} bash -c 'process_one "$@"' _ {} || true
else
    while IFS= read -r -d $'\0' file; do
        ((file_count++))
        if process_one "$file"; then
            ((processed_count++))
        fi
    done < <(find "$TARGET_DIR" -type f \( ! -name "$(basename "$OUTPUT_MD")" -a ! -name "*.py" -a ! -name "*.sh" -a ! -name ".*" \) -print0)
fi

echo "" >&2
echo "[Ring-0 v1.3] Pipeline complete. Files: $file_count | Written: $processed_count" >&2
echo "[Ring-0] Master_Ring0.md: $(wc -c < "$OUTPUT_MD") bytes" >&2

if command -v gpg >/dev/null 2>&1; then
    gpg --batch --yes --detach-sign --armor --output "${OUTPUT_MD}.sig" "$OUTPUT_MD" 2>/dev/null && \
        echo "[Ring-0] GPG provenance: ${OUTPUT_MD}.sig" >&2 || echo "[Ring-0] GPG skipped" >&2
fi

echo "[Ring-0 v1.3] READY: Memory-safe Rust extraction | Kernel XDP airgap | NotebookLM corpus" >&2
rm -f "$LOCKFILE" 2>/dev/null || true
